---
title: "test1"
author: "Koh_Jin_Jie"
date: "11/7/2020"
output: html_document
---

```{r setup, include=FALSE}

library(shiny)
library(shinythemes)
library(leaflet)
library(rgdal)
library(raster)
library(XML)
library(tidyverse)
library(ggplot2)
library(plotly)
library(scales)
library(ggmap)
library(jsonlite)
library(googleway)
library(leaflet)
library(sf)
library(shinycssloaders)
library(tidyr)
library(dplyr)
library(DT)
library(geosphere)
library(htmlwidgets)
ggmap::register_google(key = 'AIzaSyBtkpz6CUH-lwaRTLrfnBbGPpaj4pst6Z8')
setwd("C:/Users/kohji/Documents/GitHub/bto")
key <- "AIzaSyBtkpz6CUH-lwaRTLrfnBbGPpaj4pst6Z8"
set_key(key = key)
final_out <- read.csv("Resale_Region.csv")
resale_avail <- read.csv("Resale_Avail.csv")


##############################################################################################################################################################################
#DATA SOURCE & CLEANING ################################################################################################################################################################


bto <- read.csv("BTOPredict.csv")
bto[6,1] <- 6
bto[,5] <- NA
bto$X <- paste0("B",row_number(bto$X))
bto <- bto %>% rename(ID=X,`Month of Launch`=`Month.of.Launch`,`Town/Estate`=`Town.Estate`,
                      `Estimated Flats`=`Estimated.Flats`,`2-Room Flexi`=`X2.room.Flexi`,`3-Room`=`X3.room`,
                      `4-Room`=`X4.room`,`5-Room`=`X5.room`) 
resale <- read.csv("Resale_coords.csv") 
resale$X.1 <- paste0("R",resale$X.1)
resale <- resale %>% rename(ID=X.1) %>% subset(select = -c(X))
resale$Price <- (gsub("[\\$,]", "", resale$Price))

mop <- read.csv("MOP.csv")
mop$X <- paste0("M",mop$X)
mop <- mop %>% rename(ID=X,`Town/Name`=`Town.Name`,`Project Name`=`BTO.Project.Name`,
                      `Launch Date`=`Launch.Date`,`Year Completed`=`Year.of.Completion`,
                      `Studio Units`=`No.of.Studio.units`,`2-Room Units`=`No.of.2.room.units`,
                      `3-Room Units`=`No.of.3.room.units`,`4-Room Units`=`No.of.4.room.units`,
                      `5-Room Units`=`No.of.5.room.units`, `3Gen Units`=`No.of.3.gen.units`,`Total Units`=`Total.no.of.units`, 
                      `End of MOP`=`End_of_mop`) %>% subset(select=-c(idMOP))

mop <- mop[,c(1,2,3,4,14,5,6,7,8,9,10,11,12,13,15,16)] %>% select(-Type,Type)


```

```{r}
predicted_data <- read_csv("predicted_price.csv")

mop2 <- mop %>% gather(key = "flat_type", value = "num_of_units", c("Studio Units", "2-Room Units", "3-Room Units","4-Room Units", "5-Room Units", "3Gen Units" ))
mop2$flat_type <- gsub(" Units", "", mop2$flat_type)
mop2$flat_type <- gsub("Room", "ROOM", mop2$flat_type)
mop2$flat_type <- gsub("-", " ", mop2$flat_type)
mop2$flat_type <- gsub("3Gen", "EXECUTIVE", mop2$flat_type)
mop2$town <- toupper(mop2$`Town/Name`)


predicted_data_temp1 <- predicted_data[, c("town", "flat_type", "price1")]
predicted_data_final <- predicted_data_temp1 %>% group_by(town, flat_type) %>% summarise(price1= mean(price1))

mop <- merge.data.frame(x= mop2, y= predicted_data_final, by = c('flat_type', 'town'), all.x = TRUE) 
mop
bto2 <- bto %>% gather(key = "flat_type", value = "price", c("2-Room Flexi", "3-Room", "4-Room","5-Room"))
bto2$flat_type <- gsub(" Flexi", "", bto2$flat_type)
bto2$flat_type <- gsub("Room", "ROOM", bto2$flat_type)
bto2$flat_type <- gsub("-", " ", bto2$flat_type)
bto2$town<- toupper(bto2$`Town/Estate`)

 

predicted_data_temp2 <- predicted_data[, c("town", "flat_type", "price1", "resale_price")]
predicted_data_3 <- predicted_data_temp2 %>% group_by(town, flat_type, resale_price) %>% summarise(price1= mean(price1))
predicted_data_3

#predicted_data_temp2 <- predicted_data_temp2 %>% rename("price" = "resale_price") 

#bto_final <- merge.data.frame(x= bto2, y= predicted_data_temp2, by = c('flat_type', 'town', 'price' ), all.x = TRUE)

bto_final

```


```{r}

bto
bto3 <- bto %>% gather(key = "flat_type", value = "price", c("2-Room Flexi", "3-Room", "4-Room","5-Room"))
bto3 %>% filter(!is.na(bto3$price)) %>% arrange(`Town/Estate`)

```
