---
title: "DBA3702 Project HDB Data"
author: "Koh_Jin_Jie"
date: "9/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/kohji/Dropbox/DBA3702/Group Project")
library(ggmap)
library(tidyverse)
library(httr)
library(jsonlite)
library(zoo)
register_google(key = 'AIzaSyDO2qMJDoY1GhFf_yWOz1pyvvMIrE62dz8')
```



```{r warning=FALSE}
#GET HDB resale data from DATA.GOV.SG API

link <- GET(url= "https://data.gov.sg/api/action/datastore_search?resource_id=42ff9cfe-abe5-4b54-beda-c88f9bb438ee&limit=77895" ) #can stretch the limit to INF

response <- content(link, as = "text", encoding = "UTF-8")

data <- fromJSON(response)
resale_data <- data$result$records



#Clean and seperate remaining lease into years and months
resale_data$remaining_lease <- gsub("months", "", resale_data$remaining_lease)
resale_data$remaining_lease <- gsub("month", "", resale_data$remaining_lease)
resale_data <- separate(data = resale_data, col = remaining_lease, into = c("remaining_year", "remaining_month"), sep= " years ")
resale_data$remaining_year <- gsub(" years", "", resale_data$remaining_year)

#clean and separate month into year month and change NA months to 0 
resale_data <- separate(data = resale_data, col = month, into = c("year_of_sale", "month_of_sale"), sep = "-")
resale_data$remaining_month <- is.na(resale_data$remaining_month) <- 0


#change year_of_sale, month_of_sale,town and resale price to appropriate data type
resale_data$year_of_sale <- as.factor(resale_data$year_of_sale )
resale_data$town <- as.factor(resale_data$town)
resale_data$flat_type <- as.factor(resale_data$flat_type)
resale_data$resale_price <- as.numeric(resale_data$resale_price)



#Complete.cases for those with empty year_of_sale, resale price or town and 
resale_data <- resale_data[complete.cases(resale_data[, 1:2]),]
resale_data <- resale_data[complete.cases(resale_data[, 13:13]),]
resale_data <- resale_data %>% subset(!is.na(resale_price))

#Combine block and street to form address
resale_data$address <- paste(resale_data$block, resale_data$street_name, sep = " ")
resale_data$address <- paste(resale_data$address, "SINGAPORE", sep = " ")

#HARDODED: Replace CWEALTH WITH COMMONWEALTH
resale_data$address <- gsub("C'WEALTH", "COMMONWEALTH", resale_data$address)


#Group_by and summarise based on town and flat_type 
resale_temp<- resale_data %>% group_by(address, flat_type) %>% summarise("avg resale price" = mean(resale_price))

resale_temp

```



```{r}
#geocode with google API
coordinates <- geocode(location=resale_temp$address,source="google")
resale_final <- cbind(resale_temp, coordinates)
resale_final

```
```{r}
#Save geocded just to save time       
write_csv(resale_final,"C:/Users/kohji/Dropbox/DBA3702/Group Project/geocoded.csv")
resale_final2 <- read_csv("geocoded.csv")




```



```{r}

resale_final2[is.na(resale_final$lon), ]



```



