---
title: "Past BTOs"
output: html_document
---

```{r}
library(rvest)
library(tidyverse)
library(dplyr)
library(zoo)

bto_url <- "https://www.teoalida.com/singapore/btolist/"
bto_url <- url(bto_url,"rb")
page <- read_html(bto_url)
bto_table <- html_table(html_nodes(page,"table"),fill=TRUE)
bto_table_test <- bto_table[[1]]

#Rename columns to row 1 data
colnames(bto_table_test) <- c("Town Name","BTO Project Name","Launch Date","Estimated Completion Date","No.of Studio units","No.of 2-room units","No.of 3-room units","No.of 4-room units","No.of 5-room units","No.of 3-gen units","Total no.of units")
#Remove first header row
bto_table_test <- bto_table_test[2:nrow(bto_table_test),]
#Remove header rows in data
bto_table_test2 <- bto_table_test[!(bto_table_test$`BTO Project Name`==""),]

#Remove unnecessary info n BTO project name
bto_table_test2$`BTO Project Name` <- gsub("\\(.*?\\)","",bto_table_test2$`BTO Project Name`)

#Removing invalid BTO projects with names of [email protected]
bto_table_test2$`BTO Project Name` <- gsub("\\[.*?\\]","",bto_table_test2$`BTO Project Name`)
bto_table_test2 <- bto_table_test2[!(bto_table_test2$`BTO Project Name`==""),]

#Removing BTO projects that are cancelled
bto_table_test2 <- filter(bto_table_test2,(bto_table_test2$`Estimated Completion Date`!="Cancelled") & (bto_table_test2$`Estimated Completion Date` != ""))

#Cleaning the Estimated Completion Data Column 
bto_table_test2$`Estimated Completion Date` <- gsub("to","/",bto_table_test2$`Estimated Completion Date`)

#Splitting the Estimated Completion Data Column if there is more than one estimated completion date. Keep the later date of completion 
bto_table_test2 <- bto_table_test2 %>% separate(`Estimated Completion Date`,c("early completion","late completion"),"/")
bto_table_test3 <- as.data.frame(t(apply(bto_table_test2,1,zoo::na.locf)))

#Filtering out the Year of Completion to resolve date format inconsistencies
bto_table_test3$`late completion` <- sub('.*(\\d{4}).*', '\\1', bto_table_test3$`late completion`) 

#remove unnecessary columns and rename columns appropriately
bto_table_test3 <- bto_table_test3 %>% select(!`early completion`)
colnames(bto_table_test3)[4] <- "Year of Completion"

#Keeping only BTO projects that will reach their MOP after 2020(projects with year of completion being 2015 or later)
bto_mop <- filter(bto_table_test3,`Year of Completion`>=2015)
bto_mop$End_of_mop <- as.numeric(bto_mop$`Year of Completion`) + 5

bto_mop
```
### Getting postal code of BTOs from google API 
```{r}
library(ggmap)
library(dplyr)

#creating a search column 
bto_mop$bto_search <- paste0(bto_mop$`Town Name`," HDB ", bto_mop$`BTO Project Name`)

ggmap::register_google(key = 'AIzaSyBEIsoSKfWZk48Hd8TnfXm6c5wRlbIgOIM')
bto_ggmap <- geocode(location=bto_mop$bto_search,output="more",source="google")
bto_ggmap <- bind_cols(bto_mop,bto_ggmap)


incomplete_bto_ggmap <- bto_ggmap[!complete.cases(bto_ggmap),1:12] %>% mutate(address = "")
complete_bto_ggmap <- bto_ggmap[complete.cases(bto_ggmap), -13] 
incomplete_bto_ggmap$address[1] <- "81 Woodlands Cir, Singapore 738909"
incomplete_bto_ggmap$address[2] <-"102A Bidadari Park Drive"
incomplete_bto_ggmap$address[3] <- "205 Woodleigh Link 360205"
incomplete_bto_ggmap$address[4] <- "568A Champions Way, Singapore 731568"
incomplete_bto_ggmap$address[5] <- "561A Champions Way 731561"

ggmap::register_google(key = 'AIzaSyBEIsoSKfWZk48Hd8TnfXm6c5wRlbIgOIM')
incomplete_ggmap <- geocode(location=incomplete_bto_ggmap$address,output="more",source="google")

incomplete_ggmap <- bind_cols(incomplete_bto_ggmap,incomplete_ggmap)
incomplete_ggmap <- incomplete_ggmap[,-13]
names(incomplete_ggmap)[17] <- "address"


final_bto <- rbind(complete_bto_ggmap,incomplete_ggmap)
final_bto

```
### Plotting BTOs that have yet to reach MOP on leaflet
```{r}
library(leaflet)
library(tidyverse)
bto_mop_leaflet <- leaflet() %>%  addTiles() %>% 
  addMarkers(data = final_bto, lng = ~lon, lat = ~lat, popup = ~`BTO Project Name`)

bto_mop_leaflet




#Test changes
#TEST test

```