---
title: "Project Stuff"
author: "Jacob Khoo"
date: "10/11/2020"
output: html_document
---

```{r}
library(rvest)
library(dplyr)
library(httr)
library(jsonlite)
library(tidyr)
library(knitr)
library(stringr)
library(lubridate)
library(XML)
library(htmltab)
library(leaflet.extras)
library(geojsonio)
library(sf)
library(ggmap)
ggmap::register_google(key = 'AIzaSyBtkpz6CUH-lwaRTLrfnBbGPpaj4pst6Z8')
```


```{r}
urlnov <- "https://www.hdb.gov.sg/cs/infoweb/residential/buying-a-flat/new/sales-launches/bto-sbf-open-booking"
pagenov <- read_html(urlnov)
listingnov <- html_nodes(pagenov,"#UpcomingSalesLaunch-1 a")

dfnov <- url %>% htmltab(which=1)
names(dfnov) <- c("Month.of.Launch","Town/Estate","Flat Mix","Estimated.Flats")
dfnov <- dfnov %>% filter(`Town/Estate`!="Non-Mature Towns/ Estates" & `Town/Estate`!="Mature Towns/ Estates")
dfnov$`Town/Estate` <- gsub("\\s*\\([^\\)]+\\)","",dfnov$`Town/Estate`)
dfnov <- dfnov %>% mutate(`2-room Flexi` = ifelse(grepl("2-room Flexi",dfnov$`Flat Mix`),1,0))
dfnov <- dfnov %>% mutate(`3-room` = ifelse(grepl("3-room",dfnov$`Flat Mix`),1,0))
dfnov <- dfnov %>% mutate(`4-room` = ifelse(grepl("4-room",dfnov$`Flat Mix`),1,0))
dfnov <- dfnov %>% mutate(`5-room` = ifelse(grepl("5-room",dfnov$`Flat Mix`),1,0))
dfnov <- subset(dfnov, select = -c(`Flat Mix`))
dfnov$Estimated.Flats <- gsub(",","",dfnov$Estimated.Flats)
dfnov$Estimated.Flats <- as.numeric(dfnov$Estimated.Flats)
dfnov[,"URL"] <- character(0)
for (i in 1:(length(listingnov)-2))
{
  dfnov[i,]$URL <- html_attr(listingnov[i+1],"href")
}
btocurrent_ggmap <- geocode(location = dfnov[,2], output = "latlon", source = "google")
btocurrent_ggmap <- cbind(dfnov, btocurrent_ggmap)

duptimes <- c(1,1,1,1,2,1,1,1,3)

idx <- rep(1:nrow(btocurrent_ggmap), duptimes)

btocurrent_ggmap <- btocurrent_ggmap[idx,]
# Have to hard code new BTO locations as they do not have existing address
new_lon <- c(103.823202, 103.730409, 103.853475, 103.936451, 103.879971, 103.875043, 103.741634, 103.734878, 103.857508, 103.874489, 103.877345, 103.877709)
new_lat <- c(1.443867, 1.358622, 1.351645, 1.339557, 1.341481, 1.338430, 1.360283, 1.362839, 1.317723, 1.336821, 1.340324, 1.343150)
btocurrent_ggmap$lon <- new_lon
btocurrent_ggmap$lat <- new_lat

btocurrent_ggmap[5,3] <- 880
btocurrent_ggmap[6,3] <- 350
btocurrent_ggmap[6,7] <- 0
btocurrent_ggmap[10,3] <- 350
btocurrent_ggmap[10,5] <- 0
btocurrent_ggmap[11,3] <- 470
btocurrent_ggmap[11,5] <- 0
btocurrent_ggmap[12,3] <- 380
btocurrent_ggmap[12,7] <- 0
btocurrent_ggmap
```

```{r}
urlaug <- "https://esales.hdb.gov.sg/bp25/launch/20aug/bto/20AUGBTO_page_2756/about0.html"
dfaug <- urlaug %>% htmltab(which=1)

names(dfaug) <- c("Town","Project","Flat.Type","Selling.Price(No.Grants)","Selling.Price(Grants)")
dfaug$Flat.Type <- gsub("[^[:alnum:]]","",dfaug$Flat.Type)
dfaug
```


```{r}
# Primary Schools (source:data.gov.sg)
sch <- read.csv("general-information-of-schools.csv")
sch <- sch %>% filter(mainlevel_code=="PRIMARY") %>% select(school_name,address,postal_code)
sch <- sch %>% unite(address.full,c(address,postal_code), sep= " ")

ggmap::register_google(key = 'AIzaSyBtkpz6CUH-lwaRTLrfnBbGPpaj4pst6Z8')

schools_df <- data.frame(Schools = sch[,1], stringsAsFactors = FALSE)

# run the geocode function from ggmap package
schools_ggmap <- geocode(location = sch[,2], output = "latlona", source = "google")
schools_ggmap <- cbind(schools_df, schools_ggmap)

# print the results
schools_ggmap

```

```{r}
# Parks
parks <- file.path(getwd(), 'parks-kml.kml')   
#st_layers(parks)
parks <- read_sf(parks, layer = 'NATIONALPARKS')

parks$Description <- gsub(".*<th>NAME</th> <td>","", parks$Description)
parks$Description <- gsub("<.*", '', parks$Description)
parks
```

```{r}
# Leaflet map
iconssch<- awesomeIcons(icon = "whatever",
                      iconColor = "black",
                      library = "ion",
                      markerColor = "red")

iconsparks<- awesomeIcons(icon = "whatever",
                      iconColor = "black",
                      library = "ion",
                      markerColor = "green")

iconsbtocurrent <- awesomeIcons(icon = "whatever",
                      iconColor = "black",
                      library = "ion",
                      markerColor = "blue")

leaflet() %>% addTiles() %>%
addAwesomeMarkers(data=schools_ggmap, ~lon, ~lat, popup= ~Schools, label = ~Schools, icon=iconssch, group="Schools")  %>% addAwesomeMarkers(data=parks, popup = ~Description, label = ~Description, icon=iconsparks, group="Parks") %>%
addAwesomeMarkers(data=btocurrent_ggmap,~lon,~lat, popup= ~`Town/Estate`, label = ~Month.of.Launch, icon=iconsbtocurrent, group="BTOcurrent") %>% addLayersControl(overlayGroups=c("Schools","Parks","BTOcurrent")) #%>% addCircleMarkers(parents house)
#https://www.teoalida.com/singapore/hdbmap/
```
```{r}
mrturl <- "https://en.wikipedia.org/wiki/List_of_Singapore_MRT_stations"

dfmrt <- mrturl %>% htmltab(which=2, rm_nodata_cols = F)
mrt_df <- data.frame(MRT = dfmrt[,1:3], stringsAsFactors = FALSE)

mrt_df <- mrt_df %>% rename(Code.In.Operation=MRT.Alpha.numeric.code.s.....In.operation, Code.Future=MRT.Alpha.numeric.code.s.....Future, MRT.Station=MRT.Station.name....English.â...Malay)
mrt_df$Code.In.Operation <- gsub("Â","",mrt_df$Code.In.Operation)

mrt_df$Code.Future<- gsub("Â","",mrt_df$Code.Future)
mrt_df

# mrt, bus interchange, shopping malls, CCs
```

