---
title: "Try Crawling"
author: "Jacob Khoo"
date: "10/22/2020"
output: html_document
---
```{r}
library(rvest)
library(dplyr)
library(httr)
library(jsonlite)
library(tidyr)
library(knitr)
library(stringr)
library(lubridate)
library(XML)
library(htmltab)
library(leaflet.extras)
library(geojsonio)
library(sf)
library(ggmap)
library(googleway)
options(scipen=999)
ggmap::register_google(key = 'AIzaSyBtkpz6CUH-lwaRTLrfnBbGPpaj4pst6Z8')
```

```{r}
resale <- data.frame(Address=NA,Info=NA,Area=NA,Price=NA)
for (i in 1:216)
{
  url <- "https://www.srx.com.sg/search/sale/hdb?page="
  pagenum <- i
  url <- paste0(url,pagenum)
  url <- url(url, "rb")
  page <- read_html(url)
  close(url)
  listing <- html_nodes(page,".insideListingTitleRow")
  count <- length(listing)
  for (j in 1:count)
  {
    resale[j+(i-1)*count,]$Address <- html_text(html_nodes(page,".insideListingTitleRow"))[j]
    resale[j+(i-1)*count,]$Info<- html_text(html_nodes(page,".listingDetailType"))[j]
    resale[j+(i-1)*count,]$Area <- html_text(html_nodes(page,".listingDetailValues"))[j]
    resale[j+(i-1)*count,]$Price <- html_text(html_nodes(page,".adjusted-line-height"))[j]
   
  }
  Sys.sleep(runif(1,10,20))
}
resale$Address <- (gsub("[\t\n]", "", resale$Address))
resale$Price <- (gsub("[\t\n]", "", resale$Price))
resale$Info <- (gsub("[\t\n]", "", resale$Info))
resale$Area <- (gsub("[\t\n]", "", resale$Area))
resale
write.csv(resale,"Resale.csv", row.names = T)
```

```{r}
geocode(location = "Blk 311C Trivelis", output = "latlona", source = "google")
```


